# Supabase project configuration
# https://supabase.com/docs/guides/cli/config

project_id = "rjhdwidddtfetbwqolof"

[functions.process-call]
verify_jwt = false

[functions.segment-call]
verify_jwt = false
